name: MobsV4
version: '${project.version}'
main: me.orange.mobsv4.MobsV4
api-version: '1.20'
author: Elongated_Orange
commands:
  mob:
    description: Makes you a mob from the Mobs SMP
  guide:
    description: Displays info about each Mob
  mobsitems:
    description: Opens a GUI of custom items