name: MobsV3
version: '${project.version}'
main: me.orange.mobsv3.MobsV3
api-version: '1.20'
commands:
  mob:
    description: Makes you a mob from the Mobs SMP
  guide:
    description: Displays info about each Mob
  mobsitems:
    description: Opens a GUI of custom items